### ISSUE TITLE
Proposal: ability to see seconds in 'time' and 'ago' format

### ISSUE THREAD

**Issue by alex-leonhardt** [nathanhoad/react-timestamp#10]
Hi,

I was wondering if it'd be possible to add the ability to see the seconds rather than "less than a minute ago" or "a minute ago" when choosing `format='ago'` and similar to see the seconds when choosing `format='time'` ? 

I could try add that myself and do a PR but I've only just started playing with React/JS so I guess I could make that work but it'd probably be very ugly code tho.

Thanks!
Alex

**Comment by nathanhoad** [comment]
I'm adding `actualSeconds` as a prop to override the 'a few seconds ago' stuff.
