### ISSUE TITLE
Change wording when using `ago` format

### ISSUE THREAD

**Issue by fabianbaier** [nathanhoad/react-timestamp#15]
Hi,

I was noticing that using the default `ago`-format I see the wording differ in a way that makes no sense to me. E.g. when I pass a timestamp that is recent it will say `a few seconds` while when it was a few minutes ago it says `a few minutes ago`. Shouldn't it say `a few seconds ago` as well? This looks odd to me.

When looking at  https://github.com/nathanhoad/react-timestamp/blob/master/src/timestamp.js#L53 it seems to be just a minimal change that would make the whole `ago`-format more cohesive. What do you think?

Best,
Fabian

**Comment by brandonrobertz** [comment]
I just hit this and it appears to be a bug. I think it's easier to just do this using either pure moment.js with `.fromNow()` or something like https://github.com/catamphetamine/react-time-ago which supports multiple languages, etc.
