### ISSUE TITLE
Utilizing React Timestamp

### ISSUE THREAD

**Issue by lfoliveir4** [nathanhoad/react-timestamp#19]
## Error
./node_modules/react-timestamp/dist/index.mjs
Can't import the named export 'useState' from non EcmaScript module (only default export is available)

## Screen
![Captura de Tela 2019-05-20 às 01 05 50](https://user-images.githubusercontent.com/32423942/57996010-8025ef00-7a9b-11e9-8ea9-0b79163459fc.png)

"dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1",
    "react-timestamp": "^5.0.0",
  }

**Comment by nathanhoad** [comment]
I've removed the `mjs` build (in version 5.1.0) so hopefully that works better for you. Let me know if it doesn't

**Comment by lfoliveir4** [comment]
This has been solved for me:

I deleted the .mjs file inside the ./node_modules/react-timestamp/dist/index.mjs folder and changed the version in package.json to the version: "react-timestamp": "^ 4.4.0"
