### ISSUE TITLE
null is not an object (evaluating 'date.split')

### ISSUE THREAD

**Issue by pzehle** [nathanhoad/react-timestamp#5]
Hi!

I'm connecting to an API, which gives me a millisecond timestamp, so I need to divide it by 1000 to get the correct timestamp in seconds. All ok, in fact, if I put the result of my equation anywhere, it shows the timestamp as a number. Problem is that I can't use this inside <Timestamp />, it throws the next error:

null is not an object (evaluating 'date.split').

Heres my code:
```javascript
renderRow(post) {
    var correctTime = Number(post.publish_date);
    correctTime = Math.floor(correctTime / 1000);
    return(
        <TouchableHighlight>
            <View style={styles.row}>
                <Image style={styles.image} source={{uri: post.featured_image}} />
                <View style={styles.info}>
                    <Text style={styles.title}>{post.title}</Text>
                    <Text style={styles.author}>Por {post.author_name} {correctTime}</Text> {/* <--- It shows correctly here. */}
                    <Timestamp time={Number(correctTime)} component={Text} format='date' style={styles.date} /> {/* <--- Here's the problem. */}
                    <Text numberOfLines={3} style={styles.description}>{post.meta_description}..</Text>
                </View>
            </View>
        </TouchableHighlight>
    );
}
```

**Comment by nathanhoad** [comment]
Would you be able to give me an actual value for `correctTime` that I can test against? 

I've tested the component inside a ReactNative app and the only way I can get it to say `null is not an object (evaluating 'date.split')` is by giving it `Number("some string")` or `Number(undefined)` as the `time` prop.

**Comment by pzehle** [comment]
Test is with this value, which is the one I'm getting from the API, in milliseconds: **1483041600000**. I need to convert it to seconds in order to work with this module, otherwise I'm getting a date of year 4100~. Thanks!

**Comment by nathanhoad** [comment]
I get '30 Dec 2016' when I use `Number(1483041600)` as the `time` prop.

What version of `react-timestamp` are you using?

**Comment by pzehle** [comment]
Yes, if I hard-code the value it works fine, just please try to divide the value I gave you by 1000 and then use that result as the `time` prop.

**Comment by nathanhoad** [comment]
When I use this code:

```javascript
    render() {
        var correctTime = 1483041600000;
        correctTime = Math.floor(correctTime / 1000);

        return (
            <View style={styles.container}>
                <Text>Value: {correctTime}</Text>
                <Time time={Number(correctTime)} format="date" component={Text} />
            </View>
        );
    }
```

I get this on screen:

<img width="208" alt="screen shot 2017-05-16 at 9 08 02 am" src="https://cloud.githubusercontent.com/assets/78984/26083118/37cd3266-3a17-11e7-845f-22e64fb7179a.png">

**Comment by pzehle** [comment]
I'm doing exactly the same, but I'm using it inside a `renderRow()` function of a `ListView`, could you try that please?

**Comment by nathanhoad** [comment]
Components generally have no knowledge of their parent but just to make sure I tried rendering a ListView:

```javascript
    renderRow (post) {
        var correctTime = Number(post.publish_date);
        correctTime = Math.floor(correctTime / 1000);
        
        return (
            <View style={styles.cell}>
                <Text style={styles.title}>{post.title}</Text>
                <Text>Value: {correctTime}</Text>
                <Time time={Number(correctTime)} format="date" component={Text} />
            </View>
        )
    }
```

And got this:

<img width="408" alt="screen shot 2017-05-16 at 9 37 04 am" src="https://cloud.githubusercontent.com/assets/78984/26083817/45465e32-3a1b-11e7-8de6-3d680ef05d64.png">

**Comment by pzehle** [comment]
Ok. Well, I'm still getting the same error, so you can close this issue if you want, and I'm going to keep looking for a solution, if I find anything else I'll let you know. Thanks again for you support.

**Comment by nathanhoad** [comment]
Ok I'll close it for now but feel free to comment back here if you find out any more info.

**Comment by pzehle** [comment]
Ok, thanks.
