### ISSUE TITLE
Uncaught TypeError: Cannot read property 'enqueueForceUpdate' of undefined

### ISSUE THREAD

**Issue by samdenty** [nathanhoad/react-timestamp#8]
![image](https://user-images.githubusercontent.com/13242392/32983902-10927a8e-cc94-11e7-8b7f-eb0fefea2b69.png)
```js
<Timestamp time={record.timestamp}
    format='ago'
    precision={this.props.parentState.width > 600 ? 2 : 1}
    autoUpdate
/>
```

**Comment by nathanhoad** [comment]
This should be fixed in 4.3.1 - https://github.com/nathanhoad/react-timestamp/commit/809e25652b15839d0474b4c3f7390f7b51d6ea5c
